version: '3'

services:

  nfs-server:
    image: 668638571691.dkr.ecr.eu-west-1.amazonaws.com/cyclope/nfs-server-alpine
    container_name: nfs-server
    network_mode: "host"
    restart: always
    privileged: true
  #  ports: ['2049:2049']
    volumes: ['/home/dgxuser/nfsfiles/:/nfsshare']
    environment:
      SHARED_DIRECTORY: /nfsshare
